name: ngs_preprocessing_pipeline
channels:
    - conda-forge
    - bioconda
    - r
dependencies:
    - pandas==0.24.2
    - snakemake==5.5.4
    - biopython==1.70
    # R: basic tools
    - r-base==3.6
    - r-devtools==2.0.2
    - r-argparse==2.0.1
    - r-testit==0.9
    - r-readxl=1.3.1
    # R: graphics
    - r-rcolorbrewer=1.1_2
